<?php

namespace Gett\MyParcel;

class Constant
{
    const POSTNL_DEFAULT_CARRIER = 'MYPARCEL_DEFAULT_CARRIER';

    const MENU_API_SETTINGS = 0;
    const MENU_GENERAL_SETTINGS = 1;
    const MENU_LABEL_SETTINGS = 2;
    const MENU_ORDER_SETTINGS = 3;
    const MENU_CUSTOMS_SETTINGS = 4;

    const MY_PARCEL_API_KEY_CONFIGURATION_NAME = 'MY_PARCEL_API_KEY';
    const MY_PARCEL_API_LOGGING_CONFIGURATION_NAME = 'MY_PARCEL_API_LOGGING';

    const MY_PARCEL_PACKAGE_TYPE_CONFIGURATION_NAME = 'MY_PARCEL_PACKAGE_TYPE';
    const MY_PARCEL_ONLY_RECIPIENT_CONFIGURATION_NAME = 'MY_PARCEL_RECIPIENT_ONLY';
    const MY_PARCEL_AGE_CHECK_CONFIGURATION_NAME = 'MY_PARCEL_AGE_CHECK';
    const MY_PARCEL_PACKAGE_FORMAT_CONFIGURATION_NAME = 'MY_PARCEL_PACKAGE_FORMAT';

    const MY_PARCEL_RETURN_PACKAGE_CONFIGURATION_NAME = 'MY_PARCEL_RETURN_PACKAGE';
    const MY_PARCEL_SIGNATURE_REQUIRED_CONFIGURATION_NAME = 'MY_PARCEL_SIGNATURE_REQUIRED';
    const MY_PARCEL_INSURANCE_CONFIGURATION_NAME = 'MY_PARCEL_INSURANCE';
    const MY_PARCEL_CUSTOMS_FORM_CONFIGURATION_NAME = 'MY_PARCEL_CUSTOMS_FORM';
    const MY_PARCEL_CUSTOMS_CODE_CONFIGURATION_NAME = 'MY_PARCEL_CUSTOMS_CODE';
    const MY_PARCEL_CUSTOMS_ORIGIN_CONFIGURATION_NAME = 'MY_PARCEL_CUSTOMS_ORIGIN';
    const MY_PARCEL_CUSTOMS_AGE_CHECK_CONFIGURATION_NAME = 'MY_PARCEL_CUSTOMS_AGE_CHECK';

    const SINGLE_LABEL_CREATION_OPTIONS = [
        self::MY_PARCEL_PACKAGE_TYPE_CONFIGURATION_NAME,
        self::MY_PARCEL_PACKAGE_FORMAT_CONFIGURATION_NAME,
        self::MY_PARCEL_ONLY_RECIPIENT_CONFIGURATION_NAME,
        self::MY_PARCEL_AGE_CHECK_CONFIGURATION_NAME,
        self::MY_PARCEL_RETURN_PACKAGE_CONFIGURATION_NAME,
        self::MY_PARCEL_SIGNATURE_REQUIRED_CONFIGURATION_NAME,
        self::MY_PARCEL_INSURANCE_CONFIGURATION_NAME,
    ];

    const MY_PARCEL_SHARE_CUSTOMER_EMAIL_CONFIGURATION_NAME = 'MY_PARCEL_SHARE_CUSTOMER_EMAIL';
    const MY_PARCEL_SHARE_CUSTOMER_PHONE_CONFIGURATION_NAME = 'MY_PARCEL_SHARE_CUSTOMER_PHONE';

    const MY_PARCEL_LABEL_DESCRIPTION_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_DESCRIPTION';
    const MY_PARCEL_LABEL_OPEN_DOWNLOAD_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_OPEN_DOWNLOAD';
    const MY_PARCEL_LABEL_SIZE_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_SIZE';
    const MY_PARCEL_LABEL_POSITION_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_POSITION';
    const MY_PARCEL_LABEL_PROMPT_POSITION_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_PROMPT_POSITION';

    const MY_PARCEL_LABEL_CREATED_ORDER_STATUS_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_CREATED_ORDER_STATUS';

    const MY_PARCEL_CARRIER_CONFIGURATION_FIELDS = [
        'deliveryTitle',
        'dropOffDays',
        'cutoffTime',
        'deliverydaysWindow',
        'dropoffDelay',
        'allowMondayDelivery',
        'saturdayCutoffTime',
        'deliveryMorningTitle',
        'priceMorningDelivery',
        'deliveryStandardTitle',
        'priceStandardDelivery',
        'deliveryEveningTitle',
        'priceEveningDelivery',
        'signatureTitle',
        'priceSignature',
        'onlyRecipientTitle',
        'priceOnlyRecipient',
        'pickupTitle',
        'pricePickup',
        'pricePickupExpress',
        'BEdeliveryTitle',
        'MY_PARCEL_PACKAGE_TYPE',
        'MY_PARCEL_PACKAGE_FORMAT',
    ];

    const MY_PARCEL_STATUS_CHANGE_MAIL_CONFIGURATION_NAME = 'MY_PARCEL_STATUS_CHANGE_MAIL';
    const MY_PARCEL_SENT_ORDER_STATE_FOR_DIGITAL_STAMPS_CONFIGURATION_NAME = 'MY_PARCEL_SENT_ORDER_STATE_FOR_DIGITAL_STAMPS';
    const MY_PARCEL_LABEL_SCANNED_ORDER_STATUS_CONFIGURATION_NAME = 'MY_PARCEL_LABEL_SCANNED_ORDER_STATUS';
    const MY_PARCEL_DELIVERED_ORDER_STATUS_CONFIGURATION_NAME = 'MY_PARCEL_DELIVERED_ORDER_STATUS';
    const MY_PARCEL_ORDER_NOTIFICATION_AFTER_CONFIGURATION_NAME = 'MY_PARCEL_ORDER_NOTIFICATION_AFTER';
}
