name: 'Rebase pull request'

on:
  repository_dispatch:
    types: [ rebase-command ]

jobs:
  rebase:
    runs-on: ubuntu-20.04
    steps:
      - uses: peter-evans/rebase@v2
        id: rebase
        with:
          head: ${{ github.event.client_payload.pull_request.head.label }}

      - name: 'Add reaction'
        if: steps.rebase.outputs.rebased-count == 1
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          comment-id: ${{ github.event.client_payload.slash_command.args.named.comment-id }}
          reaction-type: rocket
