name: 'Run tests on pull request'

on:
  repository_dispatch:
    types: [ test-command ]

jobs:
  test:
    uses: myparcelnl/sdk/.github/workflows/test.yml@main
    with:
      ref: ${{ github.event.client_payload.pull_request.head.ref }}

  update-comment:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: 'Add reaction'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          comment-id: ${{ github.event.client_payload.slash_command.args.named.comment-id }}
          reaction-type: rocket
