name: 'Publish new version 🚀'
on:
  push:
    branches:
      - main

    paths:
      - .github/workflows/release.yml
      - .github/workflows/test.yml
      - composer.json
      - composer.lock
      - src/**/*
      - test/**/*

  workflow_dispatch:

jobs:
  test:
    name: 'Run tests 🧪'
    uses: ./.github/workflows/--test.yml
    secrets: inherit

  release:
    name: 'Release'
    runs-on: ubuntu-22.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REPO_TOKEN }}

      - uses: myparcelnl/actions/yarn2-install@v3

      - uses: myparcelnl/actions/semantic-release@v3
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
